apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /drupal-mysql-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app
  template:
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - name: myapp
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: kodeKl0ud
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: drupal-mysql-storage
      volumes:
        - name: drupal-mysql-storage
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app
  template:
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - name: drupal
        image: drupal:8.6
        env:
            - name: MYSQL_HOST
              value: drupal-mysql-service
            - name: MYSQL_DATABASE
              value: drupal_db
            - name: MYSQL_USER
              value: drupal_user
            - name: MYSQL_PASSWORD
              value: kodekl0ud
        ports:
        - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30095
  type: NodePort

--- 

apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  selector:
    app: drupal-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
