--- 
- name: Install and enable httpd server and deploy sample web page
  hosts: all
  become: yes
  tasks:
    - name: Install httpd on all servers
      yum:
        name: httpd
        state: present
    - name: Ensure httpd service is up and running
      systemd:
        name: httpd
        state: started
        enabled: true
    - name: Create index.html with content
      copy:
        content: This is a Nautilus sample file, created using Ansible!
        dest: /var/www/html/index.html
        group: apache
        owner: apache
        mode: '0644'
    - name: Deploy sample web page on all servers
      lineinfile:
        path: /var/www/html/index.html
        line: Welcome to xFusionCorp Industries!
        insertbefore: "BOF"
        