---
- name: Archive and Copy /usr/src/dba/ to /opt/dba/
  hosts: all
  become: yes
  tasks:
    - name: Create an archive of /usr/src/dba/
      archive:
        path: /usr/src/dba/
        dest: /tmp/demo.tar.gz
        format: gz
    - name: copy the archive to /opt/dba/
      copy:
        src: /tmp/demo.tar.gz
        dest: /opt/dba/demo.tar.gz
        remote_src: yes
    - name: Set user and group ownership based on ansible_host
      file:
        path: /opt/dba/demo.tar.gz        
        owner: "{{ user_owner }}"        
        group: "{{ user_owner }}"
