apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  containers:
    - name: secret-container-xfusion
      image: debian:latest
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: ecommerce-secret
          mountPath: /opt/games
  volumes:
    - name: ecommerce-secret
      secret: 
        secretName: ecommerce