---
- name: Manage ACLs
  hosts: all
  become: yes
  tasks:
    - name: Create empty file blog.txt under /opt/dba/ in app server 1
      file:
        path: /opt/dba/blog.txt
        state: touch
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == "stapp01"

    - name: Set ACL for blog.txt on app server 1
      ansible.posix.acl:
        path: /opt/dba/blog.txt
        entity: tony
        etype: group
        permissions: r
        state: present
      when: inventory_hostname == "stapp01"

    - name: Create empty file story.txt under /opt/dba/ in app server 2
      file:
        path: /opt/dba/story.txt
        state: touch
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == "stapp02"

    - name: Set ACL for story.txt on app server 2
      ansible.posix.acl:
        path: /opt/dba/story.txt
        entity: steve
        etype: user
        permissions: rw
        state: present
      when: inventory_hostname == "stapp02"

    - name: Create empty file media.txt under /opt/dba/ in app server 3
      file:
        path: /opt/dba/media.txt
        state: touch
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == "stapp03"

    - name: Set ACL for media.txt on app server 3
      ansible.posix.acl:
        path: /opt/dba/media.txt
        entity: banner
        etype: group
        permissions: rw
        state: present
      when: inventory_hostname == "stapp03"

